# DOCKERFILE IS USED IF YOU WOULD LIKE TO SETUP A STAND ALONE CONTAINER FOR YOUR
# DEVELOPMENT NEEDS WHICH INCLUDES LOCAL STORAGE.
version: '3'
services:
  app:
    stdin_open: true
    container_name: bleve-server
    image: bartmika/bleve-server:latest
    environment:
        BLEVE_SERVER_ADDRESS: 0.0.0.0:8001
        BLEVE_SERVER_HOME_DIRECTORY_PATH: /db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - vol:/db

volumes:
    vol:
