version: '3'

tasks:
  start:
    cmds:
      - docker-compose -f docker-compose.yml up

  end:
    cmds:
      - docker-compose -f docker-compose.yml down

  console:
    cmds:
      - docker exec -it bleve-server bash

  deploy:
    cmds:
      - docker build -t bmika/bleve-server:1.0 .
      - docker tag bmika/bleve-server:1.0 bmika/bleve-server:1.0
      - docker push bmika/bleve-server:1.0

  # The following task will perform a vulnerability scan on our golang project and display any issues found.
  scan:
    cmds:
      - govulncheck ./...
      - trivy image bmika/bleve-server:1.0
      - trivy repo https://github.com/bartmika/bleve-server.git

  # The following command will upgade all the dependencies in this project.
  upgrade_dep:
    cmds:
      - go get -u ./...
      - go mod tidy
