version: '3'

tasks:
  start:
    cmds:
      - docker-compose -f docker-compose.yml up

  end:
    cmds:
      - docker-compose -f docker-compose.yml down

  console:
    cmds:
      - docker exec -it bleve-server bash

  deploy:
    cmds:
      - docker build -t bartmika/bleve-server:latest .
      - docker tag bartmika/bleve-server:latest bartmika/bleve-server:latest
      - docker push bartmika/bleve-server:latest

  # The following task will perform a vulnerability scan on our golang project and display any issues found.
  scan:
    cmds:
      - govulncheck ./...
      - trivy image bartmika/bleve-server:latest
      - trivy repo https://github.com/bartmika/bleve-server.git

  # The following command will upgade all the dependencies in this project.
  upgrade_dep:
    cmds:
      - go get -u ./...
      - go mod tidy
